Repository Pmacdon15/landscape-friend, pull requests merged in 2025-08, with the labels that each got.

#12 set up nav bar
  src/components/ui/header/header.tsx
  src/components/ui/nav/nav-bar.tsx
  src/components/ui/nav/nav-menu-component.tsx
Labels: enhancement

#13 email links
  src/DAL/dal.ts
  src/app/email/error.tsx
  src/app/email/individual-preselected/[client_email]/[client_name]/page.tsx
  src/app/email/individual/page.tsx
  src/components/ui/emails/send-email-component.tsx
  src/components/ui/emails/send-email-inputs.tsx
  src/components/ui/emails/send-individual-email.tsx
  src/components/ui/fallbacks/send-individual-email-fallback.tsx
  src/components/ui/nav/nav-bar.tsx
  src/components/ui/nav/nav-menu-component.tsx
  src/lib/db.ts
  src/types/types.ts
Labels: enhancement

#19 Change image
  next.config.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/client-list/add-client-form-server-component.tsx
  src/components/ui/client-list/client-list-all.tsx
  src/components/ui/emails/send-email-component.tsx
  src/components/ui/header/header.tsx
Labels: enhancement

#21 start seo
  src/animations/landing-page.css
  src/app/email/layout.tsx
  src/app/layout.tsx
  src/app/lists/layout.tsx
  src/app/page.tsx
Labels: documentation, enhancement

#27 readme license
  .env.sample
  .gitignore
  LICENSE.md
  README.md
Labels: enhancement

#32 26 send an estimate page needs to be completed
  bun.lock
  package-lock.json
  package.json
  src/actions/sendEmails.ts
  src/actions/stripe.ts
  src/app/invoices/send-quote/page.tsx
  src/components/ui/nav/nav-menu-component.tsx
  src/components/ui/stripe-quote-form/create-quote-form.tsx
  src/lib/resend.ts
  src/mutations/mutations.ts
Labels: enhancement

#41 35 a page to manage invoices
  SQL/schema.sql
  src/DAL/dal.ts
  src/actions/stripe.ts
  src/app/billing/layout.tsx
  src/app/billing/manage/invoices/error.tsx
  src/app/billing/manage/invoices/page.tsx
  src/app/billing/send-quote/error.tsx
  src/app/billing/send-quote/page.tsx
  src/app/lists/clearing/error.tsx
  src/app/lists/clearing/loading.tsx
  src/app/lists/clearing/page.tsx
  src/app/lists/client/page.tsx
  src/app/lists/cutting/page.tsx
  src/components/ui/buttons/manage-invoice-button.tsx
  src/components/ui/client-list/client-list-all.tsx
  src/components/ui/client-list/search-form.tsx
  src/components/ui/containers/form-container.tsx
  src/components/ui/date-display.tsx
  src/components/ui/header/header.tsx
  src/components/ui/inputs/search-input.tsx
  src/components/ui/manage-invoices/manage-invoices-card-view.tsx
  src/components/ui/nav/nav-menu-component.tsx
  src/components/ui/pagination.tsx
  src/components/ui/pagination/pagination-tabs.tsx
  src/components/ui/selectors/cutting-period-selector.tsx
  src/components/ui/selectors/invoice-status-selector.tsx
  src/components/ui/selectors/service-status-selector.tsx
  src/components/ui/service-list/clients-list-service.tsx
  src/components/ui/service-list/service-list-date-picker.tsx
  src/hooks/hooks.ts
  src/lib/db.ts
  src/lib/params.ts
  src/middleware.ts
  src/mutations/mutations.ts
  src/types/types.ts
Labels: enhancement

#43 30 add amount of clients allowed to db
  SQL/schema.sql
  src/actions/clients.ts
  src/lib/db.ts
Labels: enhancement

#45 Using Stripe API Key
  src/DAL/dal.ts
Labels: enhancement

#46 Site Map Component
  SQL/schema.sql
  bun.lock
  package-lock.json
  package.json
  src/DAL/dal-map-component.ts
  src/actions/blobs.ts
  src/app/layout.tsx
  src/app/lists/clearing/page.tsx
  src/app/lists/cutting/page.tsx
  src/components/ui/buttons/set-view-map-button.tsx
  src/components/ui/buttons/upload-image-button.tsx
  src/components/ui/client-list/client-list-all.tsx
  src/components/ui/client-list/search-form.tsx
  src/components/ui/header/header.tsx
  src/components/ui/image-list/image-gallery.tsx
  src/components/ui/image-list/image-list.tsx
  src/components/ui/image-list/list-view/add-site-map.tsx
  src/components/ui/image-list/list-view/image-list-view.tsx
  src/components/ui/image-list/list-view/list-view-header.tsx
  src/components/ui/image-list/list-view/list-view-warapper.tsx
  src/components/ui/image-selector/image-selector-main.tsx
  src/components/ui/image-uploader/image-uploader.tsx
  src/components/ui/inputs/image-upload-input.tsx
  src/components/ui/map-component/map-component.tsx
  src/components/ui/nav/nav-bar.tsx
  src/components/ui/nav/nav-menu-component.tsx
  src/components/ui/service-list/clients-list-service.tsx
  src/components/ui/sonner.tsx
  src/lib/db.ts
  src/lib/image-selector-helpers.ts
  src/lib/params.ts
  src/lib/sort.ts
  src/lib/upload.ts
  src/lib/zod/schemas.ts
  src/mutations/mutations.ts
  src/types/types.ts
Labels: enhancement

#49 added is admin check for ui update and place holder image for empty and non admin
  SQL/schema.sql
  src/app/lists/clearing/page.tsx
  src/app/lists/client/page.tsx
  src/app/lists/cutting/page.tsx
  src/components/ui/client-list/client-list-all.tsx
  src/components/ui/image-list/image-list.tsx
  src/components/ui/image-list/list-view/list-view-warapper.tsx
  src/components/ui/image-list/list-view/non-admin-placeholder.tsx
  src/components/ui/service-list/clients-list-service.tsx
Labels: enhancement

#54 Client List UI Update first pass
  public/client-list/address.png
  public/client-list/email.png
  public/client-list/telephone.png
  src/DAL/actions/stripe.ts
  src/app/lists/client/page.tsx
  src/app/page.tsx
  src/components/ui/client-list/client-list-all.tsx
  src/components/ui/cutting-week/cutting-week.tsx
  src/types/types-stripe.ts
Labels: enhancement

#55 Added delete sitemap button
  package-lock.json
  src/DAL/actions/clients.ts
  src/components/ui/alerts/alert.tsx
  src/components/ui/buttons/delete-site-map-button.tsx
  src/components/ui/image-list/image-gallery.tsx
  src/components/ui/image-list/list-view/image-list-view.tsx
  src/components/ui/pagination/pagination-tabs.tsx
  src/lib/DB/db-clients.ts
  src/lib/zod/schemas.ts
  src/mutations/mutations.ts
  src/types/types-clients.ts
Labels: enhancement

#57 Added Novu for notifactions
  SQL/schema.sql
  src/DAL/dal-novu.ts
  src/DAL/dal-user.ts
  src/app/page.tsx
  src/components/ui/buttons/text-add-novu-sub-button.tsx
  src/components/ui/header/header.tsx
  src/lib/novu.ts
  src/lib/webhooks.ts
Labels: enhancement

#69 added documentation page
  src/app/documentation/page.tsx
Labels: documentation, enhancement

#70 39 create stripe webhooks
  SQL/schema.sql
  src/app/api/webhooks/stripe/[orgId]/route.ts
  src/app/page.tsx
  src/components/ui/test/test-add-stripe-webhook.tsx
  src/lib/DB/db-clients.ts
  src/lib/DB/db-stripe.ts
  src/lib/actions/clients-action.ts
  src/lib/actions/stripe-action.ts
  src/lib/actions/stripe-actions.ts
  src/lib/dal/stripe-dal.ts
  src/lib/hooks/useStripe.ts
  src/lib/server-funtions/resend.ts
  src/lib/server-funtions/stripe-utils.ts
  src/lib/webhooks/stripe-webhooks.ts
  src/middleware.ts
Labels: enhancement

#74 Added Edit invoice page
  SQL/schema.sql
  src/app/billing/edit/invoice/error.tsx
  src/app/billing/edit/invoice/loading.tsx
  src/app/billing/edit/invoice/page.tsx
  src/components/ui/buttons/manage-invoice-button.tsx
  src/components/ui/fallbacks/edit-invoice-form-fallback.tsx
  src/components/ui/links/edit-invoice-link.tsx
  src/components/ui/manage/invoices/manage-invoices-card-view.tsx
  src/components/ui/stripe-forms/shared/alert-message.tsx
  src/components/ui/stripe-forms/shared/dynamic-fields.tsx
  src/components/ui/stripe-forms/shared/input.tsx
  src/components/ui/stripe-invoice-form/edit-invoice-form.tsx
  src/components/ui/stripe-quote-form/create-quote-form.tsx
  src/lib/actions/stripe-action.ts
  src/lib/dal/stripe-dal.ts
  src/lib/mutations/mutations.ts
  src/lib/zod/schemas.ts
  src/types/types-stripe.ts
Labels: enhancement

#77 72 bug triggering notifactions on invoice send
  src/app/api/webhooks/stripe/[orgId]/route.ts
  src/lib/server-funtions/novu.ts
Labels: bug, enhancement

#80 Passing payload to notifactions
  SQL/schema.sql
  src/app/api/webhooks/stripe/[orgId]/route.ts
  src/components/ui/header/header.tsx
  src/components/ui/stripe-invoice-form/edit-invoice-form.tsx
  src/lib/mutations/mutations.ts
  src/lib/server-funtions/novu.ts
  src/lib/server-funtions/stripe-utils.ts
  src/types/webhooks-types.ts
Labels: enhancement

#81 76 bug form clears when you edit a invoice
  src/app/billing/edit/invoice/page.tsx
  src/app/billing/send-quote/page.tsx
  src/components/ui/links/back-to-link.tsx
  src/components/ui/stripe-forms/stripe-invoice-form/edit-invoice-form.tsx
  src/components/ui/stripe-forms/stripe-quote-form/create-quote-form.tsx
  src/lib/actions/stripe-action.ts
  src/lib/hooks/hooks.ts
  src/lib/zod/schemas.ts
Labels: bug

#82 Add notifaction link to manage invoices
  src/app/api/webhooks/stripe/[orgId]/route.ts
  src/lib/actions/stripe-action.ts
  src/lib/dal/stripe-dal.ts
  src/lib/hooks/hooks.ts
  src/lib/server-funtions/novu.ts
  src/types/types-stripe.ts
  src/types/webhooks-types.ts
Labels: enhancement

#88 Add some notifications for quote actions
  src/app/globals.css
  src/components/ui/buttons/manage-invoice-button.tsx
  src/components/ui/buttons/manage-quote-button.tsx
  src/components/ui/buttons/submit-add-client-to-list.tsx
  src/components/ui/buttons/update-stripe-api-key-button.tsx
  src/components/ui/buttons/upload-image-button.tsx
  src/components/ui/header/header.tsx
  src/components/ui/image-selector/image-selector-main.tsx
  src/components/ui/loaders/EllipsisSpinner.tsx
  src/components/ui/loaders/spinner.tsx
  src/components/ui/stripe-forms/stripe-invoice-form/edit-form.tsx
  src/components/ui/stripe-forms/stripe-quote-form/create-quote-form.tsx
  src/lib/actions/stripe-action.ts
  src/lib/server-funtions/novu.ts
  src/lib/server-funtions/stripe-utils.ts
Labels: enhancement

#91 a user can get a notification when a client is deleted
  src/lib/actions/clients-action.ts
Labels: enhancement

#92 87 user clean up on webhook event userdeleted
  SQL/schema.sql
  bun.lock
  package.json
  src/app/api/register-device/route.ts
  src/app/api/webhooks/clerk/route.ts
  src/app/api/webhooks/stripe/[orgId]/route.ts
  src/app/billing/create-quote/page.tsx
  src/app/billing/manage/invoices/page.tsx
  src/app/billing/manage/quotes/page.tsx
  src/app/lists/clearing/page.tsx
  src/app/lists/client/page.tsx
  src/app/lists/cutting/page.tsx
  src/components/providers/fcm-provider.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/map-component/map-component.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/pagination.tsx
  src/components/ui/stripe-forms/shared/alert-message.tsx
  src/lib/DB/db-org.ts
  src/lib/DB/db-resend.ts
  src/lib/DB/db-stripe.ts
  src/lib/actions/blobs-action.ts
  src/lib/actions/clerk-actions.ts
  src/lib/actions/clients-action.ts
  src/lib/actions/cuts-action.ts
  src/lib/actions/novu-action.ts
  src/lib/actions/sendEmails-action.ts
  src/lib/actions/snow-action.ts
  src/lib/actions/stripe-action.ts
  src/lib/dal/clients-dal.ts
  src/lib/dal/novu-dal.ts
  src/lib/dal/stripe-dal.ts
  src/lib/hooks/hooks.ts
  src/lib/utils/clerk.ts
  src/lib/utils/geocode.ts
  src/lib/utils/image-control.ts
  src/lib/utils/novu.ts
  src/lib/utils/params.ts
  src/lib/utils/resend.ts
  src/lib/utils/sort.ts
  src/lib/utils/stripe-utils.ts
  src/lib/utils/users.ts
  src/lib/utils/utils.ts
  src/lib/utils/uuid.ts
  src/lib/webhooks/clerk-webhooks.ts
  src/middleware.ts
Labels: enhancement
